<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'Nohex\\Eix' => array($baseDir . '/src/php/main', $vendorDir . false, $baseDir . '/src/php/test'),
    'Nohex\\' => array($vendorDir . '/nohex/eix/src/php/main', $vendorDir . '/nohex/eix/src/php/test'),
);
